// examples/with-nextjs/components/wallet-connect-button.tsx
import { useAuth } from '@micro-stacks/react';

export const WalletConnectButton = () => {
  const { openAuthRequest, isRequestPending, signOut, isSignedIn } = useAuth();
  const label = isRequestPending ? 'Loading...' : isSignedIn ? 'Sign out' : 'Connect Stacks wallet';
  return (
    <button
      onClick={async () => {
        if (isSignedIn) await signOut();
        else await openAuthRequest();
      }}
    >
      {label}
    </button>
  );
};

// examples/with-solidjs-ts/src/components/wallet-connect-button.tsx
import { useAuth } from '@micro-stacks/solidjs';
import { Show } from 'solid-js';

export const WalletConnectButton = () => {
  const { openAuthRequest, signOut, isRequestPending, isSignedIn } = useAuth();

  const label = (
    <Show
      when={isRequestPending()}
      fallback={
        <Show
          when={!isSignedIn()}
          fallback={'Sign out'}
        >
          Connect Stacks Wallet
        </Show>
      }
    >
      Loading...
    </Show>
  );
  return (
    <button
      onClick={() => {
        if (isSignedIn()) void signOut();
        else void openAuthRequest();
      }}
    >
      {label}
    </button>
  );
};
