// examples/with-svelte/src/components/network-toggle.svelte
<script lang='ts'>
  import { geNetwork } from '@micro-stacks/svelte';

  const network = geNetwork();

  $: label = $network.isMainnet
    ? 'mainnet'
    : 'testnet';

  function onClick() {
    $network.setNetwork($network.isMainnet ? 'testnet' : 'mainnet');
  }
</script>

<button on:click={onClick}>
  {label}
</button>

// examples/with-vue-ts/src/components/NetworkToggle.vue
<script setup lang="ts">
import { useNetwork } from '@micro-stacks/vue';

const { setNetwork, isMainnet } = $(useNetwork());

const onClick = () => {
  setNetwork(isMainnet ? 'testnet' : 'mainnet');
};
</script>

<template>
  <button
    type="button"
    v-on:click="() => onClick()"
  >
    {{ isMainnet ? 'mainnet' : 'testnet' }}
  </button>
</template>
