// examples/with-nextjs/components/wallet-connect-button.tsx
import { useAuth } from '@micro-stacks/react';

export const WalletConnectButton = () => {
  const { openAuthRequest, isRequestPending, signOut, isSignedIn } = useAuth();
  const label = isRequestPending ? 'Loading...' : isSignedIn ? 'Sign out' : 'Connect Stacks wallet';
  return (
    <button
      onClick={async () => {
        if (isSignedIn) await signOut();
        else await openAuthRequest();
      }}
    >
      {label}
    </button>
  );
};

// examples/with-vue-ts/src/components/WalletConnectButton.vue
<script setup lang="ts">
import { useAccount, useAuth } from '@micro-stacks/vue';

const { isSignedIn, isRequestPending, signOut, openAuthRequest } = $(useAuth());
const { stxAddress } = $(useAccount());

const onClick = () => (!isSignedIn ? openAuthRequest() : signOut());
</script>

<template>
  <h1>{{ stxAddress ? stxAddress : 'No session active' }}</h1>
  <button
    type="button"
    v-on:click="() => onClick()"
  >
    {{ isRequestPending ? 'pending...' : isSignedIn ? 'sign out' : 'connect stacks wallet' }}
  </button>
</template>
