// examples/with-svelte/src/components/wallet-connect-button.svelte
<script lang='ts'>
  import { getAccount, getAuth } from '@micro-stacks/svelte';

  const auth = getAuth();

  $: label = $auth.isRequestPending
    ? 'Loading...'
    : $auth.isSignedIn
      ? 'Sign out'
      : 'Connect Stacks wallet';

  function onClick() {
    if ($auth.isSignedIn) {
      $auth.signOut();
    } else {
      $auth.openAuthRequest();
    }
  }

  const account = getAccount();

  $: sessionStatus = !$account.stxAddress ? 'No active session' : $account.stxAddress;

</script>

<main>
  <h2>{sessionStatus}</h2>
  <button on:click={onClick}>
    {label}
  </button>
</main>

// examples/with-vue-ts/src/components/WalletConnectButton.vue
<script setup lang="ts">
import { useAccount, useAuth } from '@micro-stacks/vue';

const { isSignedIn, isRequestPending, signOut, openAuthRequest } = $(useAuth());
const { stxAddress } = $(useAccount());

const onClick = () => (!isSignedIn ? openAuthRequest() : signOut());
</script>

<template>
  <h1>{{ stxAddress ? stxAddress : 'No session active' }}</h1>
  <button
    type="button"
    v-on:click="() => onClick()"
  >
    {{ isRequestPending ? 'pending...' : isSignedIn ? 'sign out' : 'connect stacks wallet' }}
  </button>
</template>
