// examples/with-vue-ts/src/components/NetworkToggle.vue
<script setup lang="ts">
import { useNetwork } from '@micro-stacks/vue';

const { setNetwork, isMainnet } = $(useNetwork());

const onClick = () => {
  setNetwork(isMainnet ? 'testnet' : 'mainnet');
};
</script>

<template>
  <button
    type="button"
    v-on:click="() => onClick()"
  >
    {{ isMainnet ? 'mainnet' : 'testnet' }}
  </button>
</template>

// examples/with-react/src/components/network-toggle.jsx
import { useNetwork } from '@micro-stacks/react';

export const NetworkToggle = () => {
  const { isMainnet, setNetwork } = useNetwork();
  const networkMode = isMainnet ? 'mainnet' : 'testnet';

  return (
    <div>
      <h4>current network: {networkMode}</h4>
      <button onClick={() => setNetwork(isMainnet ? 'testnet' : 'mainnet')}>switch network</button>
    </div>
  );
};
