// examples/with-vue/src/components/WalletConnectButton.vue
<script setup lang="ts">
import { useAccount, useAuth } from '@micro-stacks/vue';

const auth = $(useAuth());
const account = $(useAccount());

const onClick = () => {
  !auth.isSignedIn ? auth.openAuthRequest() : auth.signOut();
};
</script>

<template>
  <h1>{{ account.stxAddress }}</h1>
  <button type="button" @click="() => onClick()">
    {{
      auth.isRequestPending ? 'pending...' : auth.isSignedIn ? 'sign out' : 'connect stacks wallet'
    }}
  </button>
</template>

// examples/with-nextjs/components/wallet-connect-button.tsx
import { useAuth } from '@micro-stacks/react';

export const WalletConnectButton = () => {
  const { openAuthRequest, isRequestPending, signOut, isSignedIn } = useAuth();
  const label = isRequestPending ? 'Loading...' : isSignedIn ? 'Sign out' : 'Connect Stacks wallet';
  return (
    <button
      onClick={async () => {
        if (isSignedIn) await signOut();
        else await openAuthRequest();
      }}
    >
      {label}
    </button>
  );
};
