// examples/with-solidjs-ts/src/components/user-card.tsx
import { useAccount } from '@micro-stacks/solidjs';
import { Show } from 'solid-js';

export const UserCard = () => {
  const { stxAddress } = useAccount();
  return (
    <div class={'user-card'}>
      <Show
        when={stxAddress()}
        fallback={<h3>No active session</h3>}
      >
        <h3>{stxAddress()}</h3>
      </Show>
    </div>
  );
};

// examples/with-react-jotai-ts/src/components/user-card.tsx
import { useAccountState } from '@micro-stacks/jotai';

export const UserCard = () => {
  const { stxAddress } = useAccountState();
  if (!stxAddress)
    return (
      <div className={'user-card'}>
        <h3>No active session</h3>
      </div>
    );
  return (
    <div className={'user-card'}>
      <h3>{stxAddress}</h3>
    </div>
  );
};
